version: 0.2
phases:
  install:
    commands:
      - apt-get update
      - apt-get install -y libX11-xcb-dev
      - npm install
  pre_build:
    commands:
  build:
    commands:
      - node build.js
  post_build:
    commands:
artifacts:
  files:
    - output.pdf
